### ISSUE TITLE
Convert letters?

### ISSUE THREAD

**Issue by ghost** [SamLeatherdale/discordtextgenerator#1]
Thanks for this! It is great although I didn't like how the A and B characters were red so had to play around with the javascript file for a while.

However what exactly is "Convert letters" supposed to do? All it seems to do is output the exact same as the input and I haven't figured out what it does.

Thanks!

**Comment by SamLeatherdale** [comment]
Hi there, thanks for asking.

If you open up discord and type `:a:` and send it, it converts the letter to their emoji equivalent. Quite a few other apps like Slack do it as well, it looks like even GitHub does it: :a: 

That's the main point of the script. It's just to "emojify" the text for Discord and other chat apps that use the colon format.

Since discord has a message length limit, it also breaks long messages into pieces.

**Comment by ghost** [comment]
Thanks or the reply! I understand what you mean but still don't understand what the "Split" function does. Convert works as expected but no matter my normal alphanumeric input, Split just outputs the same I put in... or is the split functionality for something else?

**Comment by SamLeatherdale** [comment]
Hi

Split just splits long messages into multiple messages. The default limit is 2000 characters, so if your message is shorter than that, you won't see any difference, but you can change the character limit for splitting messages in the Advanced options.

**Comment by ghost** [comment]
Hey, the text still splits regardless of if the slider is on "Convert" or "Split", but "Convert" shows actual converted content and "Split" shows the same as the input, stilll split.

**Comment by SamLeatherdale** [comment]
Yes, that's correct, convert also splits, as you wouldn't be able to send the message on Discord if it didn't split. I might update the button text to reflect this.
